### ISSUE TITLE
Switch statement braces are kept on the same line with Allman style

### ISSUE THREAD

**Issue by MartaWild** [ony3000/prettier-plugin-brace-style#37] opened 2024-07-03 12:43 UTC
## Dependency information
```
"prettier": "^3.3.2",
"prettier-plugin-brace-style": "^0.6.2"`
```
## Steps to reproduce
1. Enable `"braceStyle": "allman"`.
2. Write a switch statement.
3. Format code.

## The current behavior
Curly braces are kept on the same line for `switch` statement.
![image](https://github.com/ony3000/prettier-plugin-brace-style/assets/47245850/bcb432fe-1e57-440f-b0ed-72bdadb1dfc8)

## The expected behavior
Curly braces moved to a new line, as with `if` statements.
![image](https://github.com/ony3000/prettier-plugin-brace-style/assets/47245850/0d7843e0-ebf1-4471-b7d0-85524aeb3f55)

Thanks for the great library!

**Comment by ony3000** [comment] 2024-07-05 14:46
Hello! Thanks for reporting the issue!

This plugin is theoretically equivalent to applying ESLint formatting (`brace-style` only) after applying Prettier formatting.

Keeping the opening brace of a `case` block on the same line is not a bug in that sense. However, after checking through the test code, there seems to be no problem with the theoretical output even if the opening brace is moved to the next line. So this may be fixed in the next release.

It's a bug that the opening braces of the `switch` block stay on the same line. However, I can't reproduce this issue.

Can you provide more details? It would be helpful to investigate the issue to know "if you are also using other Prettier plugins" and "how Prettier is configured".

**Comment by MartaWild** [comment] 2024-07-11 14:13
Sorry! It seems the issue was related to my setup. I can't reproduce it in a fresh project, and it appears to be highly unstable in my current one. The issue can be closed.

**Closed** 2024-07-11 14:14 UTC
Labels: bug, question

**Comment by ony3000** [comment] 2024-08-16 16:00
@MartaWild `v0.7.0` has been released!

Now the opening brace of a `case` block can also breaks into new lines, check it out!

**Comment by nogeenkopjethee** [comment] 2024-12-24 14:28
I can reproduce the issue with the `switch` statement, when accessing a member or running a function in the expression.

Example 1: gets formatted correctly.

```ts
export const testFunction = (test: string) =>
{
	switch (test)
	{
		case "potato":
			return "potato";
		case "apple":
			return "apple";
		default:
			return "unknown";
	}
};

```

Example 2: it doesn't get formatted correctly.

```ts
export const testFunction = (test: string) =>
{
	switch (test.toLowerCase()) {
		case "potato":
			return "potato";
		case "apple":
			return "apple";
		default:
			return "unknown";
	}
};
```
