### ISSUE TITLE
Strange Behavior for Stroustrup

### ISSUE THREAD

**Issue by lvn921** [ony3000/prettier-plugin-brace-style#25] opened 2024-02-07 17:21 UTC
## Dependency information
package.json
```
"dependencies": {
        "react": "^18.2.0",
        "react-dom": "^18.2.0"
    },
    "devDependencies": {
        "@figma/plugin-typings": "^1.76.0",
        "@prettier/sync": "^0.5.1",
        "@types/react": "^18.2.43",
        "@types/react-dom": "^18.2.17",
        "@typescript-eslint/eslint-plugin": "^6.14.0",
        "@typescript-eslint/parser": "^6.14.0",
        "@vitejs/plugin-react": "^4.2.1",
        "eslint": "^8.55.0",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-react-refresh": "^0.4.5",
        "prettier": "^3.2.5",
        "prettier-plugin-brace-style": "^0.5.0",
        "prop-types": "^15.8.1",
        "typescript": "^5.2.2",
        "vite": "^5.0.8",
        "vite-plugin-singlefile": "^0.13.5"
    }
```

.prettierrc
```
{
    "semi": true,
    "trailingComma": "none",
    "singleQuote": true,
    "tabWidth": 4,
    "printWidth": 100,
    "plugins": ["prettier-plugin-brace-style"],
    "braceStyle": "stroustrup"
}
```

## Steps to reproduce

1. Create an empty function.
2. Make sure prettier is enabled to format on save file.
3. Save.

## The current behavior
I have an empty code block like the following:
```
registerCallbacks() {}
```
When I save my file, it changes it to the following:
```
}
egisterCallbacks() {}
```

If I uninstall the plugin, the bug doesn't happen anymore. Is it conflicting with something else in VS code?

## The expected behavior
No change to the code block on save.

**Comment by ony3000** [comment] 2024-02-07 23:41
That's strange. I can't reproduce this issue.

All tests containing empty functions pass, and formatting in VS Code works as expected.

Can you provide more details?

**Comment by lvn921** [comment] 2024-02-08 00:17
I do have eslint in the package as well. 

.eslintrc.cjs
```
module.exports = {
    root: true,
    env: { browser: true, es2015: true, node: true },
    extends: ['eslint:recommended', 'plugin:react-hooks/recommended'],
    ignorePatterns: ['dist', '.eslintrc.cjs'],
    parser: '@typescript-eslint/parser',
    plugins: ['react-refresh']
};
```
tsconfig.json
```
{
    "compilerOptions": {
        "allowJs": true,
        "target": "ES2015",
        "useDefineForClassFields": true,
        "lib": ["ES2015", "DOM", "DOM.Iterable"],
        "module": "ES2020",
        "skipLibCheck": true,
        "typeRoots": ["./src/typings", "./node_modules/@types"],

        /* Bundler mode */
        "moduleResolution": "bundler",
        "allowImportingTsExtensions": true,
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "react-jsx",
        "sourceMap": true,
        "outDir": "./dist",

        /* Linting */
        "strict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noFallthroughCasesInSwitch": true
    },
    "include": ["src", "lib"],
    "references": [{ "path": "./tsconfig.node.json" }]
}
```
Could any of these be conflicting?

I ran prettify on my entire package and everywhere there was an empty function it would do the same thing.

**Comment by ony3000** [comment] 2024-02-08 12:20
Even after adding the provided eslintrc and tsconfig, the problem still cannot be reproduced in my environment.

Can you provide the minimum repository to reproduce the issue?

**Comment by lvn921** [comment] 2024-02-08 16:21
Unfortunately, I cannot as it pertains to a my work. Do you have the prettier vs code plugin installed? Can you try that? I think maybe the plugin isn't working correctly or mine isn't set up correctly. When I uninstall it, but run prettier through cli, it's fine. However, the format-on-save is what keeps causing the issue.

v10.1.0

```
"prettier.arrowParens": "always"
"prettier.bracketSameLine": true
"prettier.embeddedLanguageFormatting": "auto"
"prettier.enable": true
"prettier.endOfLine": "lf"
"prettier.htmlWhitespaceSensitivity": "css"
"prettier.printWidth": 100
"prettier.proseWrap": "preserve"
"prettier.quoteProps": "as-needed"
"prettier.semi": true
"prettier.singleQuote": true
"prettier.tabWidth": 4
"prettier.trailingComma": "es5"
```

**Comment by ony3000** [comment] 2024-02-09 03:38
I'm sorry if there was any misunderstanding. When I said "provide the minimum repository", I didn't mean give me access to your private code. This meant providing the minimum code snippet to reproduce the issue and a separate repository that didn't contain business secrets.

I also have the Prettier VS Code extension (v10.1.0) installed, and `"editor.formatOnSave": true` is also set. In my case, I specify project-specific settings in a Prettier config file, so I left the VS Code extension's settings untouched and at their default values.

**Comment by lvn921** [comment] 2024-02-14 17:34
Hi sorry, I will try to provide a minimum repo for you as soon as I can. I'm currently swamped with work and life at the moment. Thank you for being patient with me.

**Comment by bryceosterhaus** [comment] 2024-05-09 08:28
I've also run into this issue. [I created a repo for reproduction here](https://github.com/bryceosterhaus/prettier-plugin-brace-style-bug/tree/main)

Before:
```js
class BaseQueue {
	onFlush() {}

	onFlushFail() {}

	onFlushSuccess() {}
}
```

After:
```js
class BaseQueue {
  }
  nFlush() {}

  }
  nFlushFail() {}

  }
  nFlushSuccess() {}
}

```

**Comment by ony3000** [comment] 2024-05-09 14:41
@bryceosterhaus Thanks for your reproduction. I can finally investigate this issue!

**Comment by ony3000** [comment] 2024-05-11 08:24
@lvn921 @bryceosterhaus Fixed in `v0.6.1`, check it out!

**Comment by bryceosterhaus** [comment] 2024-05-13 05:56
Thanks @ony3000!

**Comment by bryceosterhaus** [comment] 2024-05-13 08:59
@ony3000 I'm now seeing another oddity.

```
const renderComponent = ({handleSubmit = () => {}, errors}) => {
	const ref = React.createRef();

	return render(
		<StyleErrorsContextProvider initialState={errors}>
			<PublishButton formRef={ref} handleSubmit={handleSubmit} />
		</StyleErrorsContextProvider>
	);
};
```

This ends up formatting to

**Closed** 2024-05-15 07:19 UTC
Labels: bug, lang: js/ts
